name: Docker Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: nuxt-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker Image
      run: |
        docker images
        echo "Docker Image wurde erfolgreich gebaut"