name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["NPM Build"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt site
        run: npm run generate

      - name: Detailed Directory Structure
        run: |
          echo "Complete project directory structure:"
          find . -type d -not -path "*/node_modules/*" | sort
          
          echo "Root directory contents:"
          ls -la
          
          echo ".output directory contents:"
          ls -la .output || echo ".output not found"
          
          if [ -d ".output" ]; then
            echo ".output/public contents:"
            ls -la .output/public || echo ".output/public not found"
          fi
          
          echo "server directory contents:"
          ls -la server || echo "server not found"
          
          if [ -d "server" ]; then
            echo "server/.output contents:"
            ls -la server/.output || echo "server/.output not found"
            
            if [ -d "server/.output" ]; then
              echo "server/.output/public contents:"
              ls -la server/.output/public || echo "server/.output/public not found"
            fi
          fi

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3