name: Nuxt.JS Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nuxt.js
        run: npm install
      - name: Build Nuxt.ks
        run: num run generate
      - name: Deploy to Github Pages
        uses: peadeiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public